geonetwork:
  core:
    url: http://localhost:8080/geonetwork
  index:
    url: http://localhost:9200
    indexPrefix: gn5-
    indexRecordName: gn5-records
  indexing:
    chunksize: 1000
    poolsize: 10
    # Elasticsearch Bulk Async API
    asynchronous: false
  openapi:
    url: http://localhost:7979
  settings:
    system:
      metadata:
        prefergrouplogo: true

server:
  port: 7979
  servlet:
    context-path: /
  forward-headers-strategy: framework

spring:
  application:
    name: GeoNetwork
  datasource:
    url: jdbc:postgresql://localhost:5432/gn
    driverClassName: org.postgresql.Driver
    username: www-data
    password: www-data
  #      url: jdbc:h2:mem:gn5
  #      driverClassName: org.h2.Driver
  #      username: sa
  #      password: password
  jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    gateway:
      mvc:
        routes:
          - id: geonetwork_proxy_redirect
            uri: ${geonetwork.openapi.url}
            predicates:
              - Path=/geonetwork/proxy
            filters:
              - RewritePath=/geonetwork/(?<url>.*), /api/$\{url}
          - id: geonetwork_route
            uri: ${geonetwork.core.url}
            predicates:
              - Path=/geonetwork/**
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /doc/api/


debug: false
