/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GroupOperations
 */
export interface GroupOperations {
  /**
   *
   * @type {number}
   * @memberof GroupOperations
   */
  group?: number;
  /**
   *
   * @type {{ [key: string]: boolean; }}
   * @memberof GroupOperations
   */
  operations?: { [key: string]: boolean };
}

/**
 * Check if a given object implements the GroupOperations interface.
 */
export function instanceOfGroupOperations(
  value: object
): value is GroupOperations {
  return true;
}

export function GroupOperationsFromJSON(json: any): GroupOperations {
  return GroupOperationsFromJSONTyped(json, false);
}

export function GroupOperationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GroupOperations {
  if (json == null) {
    return json;
  }
  return {
    group: json['group'] == null ? undefined : json['group'],
    operations: json['operations'] == null ? undefined : json['operations'],
  };
}

export function GroupOperationsToJSON(value?: GroupOperations | null): any {
  if (value == null) {
    return value;
  }
  return {
    group: value['group'],
    operations: value['operations'],
  };
}
