/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Language
 */
export interface Language {
  /**
   *
   * @type {string}
   * @memberof Language
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof Language
   */
  inspire?: boolean;
  /**
   *
   * @type {string}
   * @memberof Language
   */
  inspireJPAWorkaround?: string;
  /**
   *
   * @type {string}
   * @memberof Language
   */
  name?: string;
}

/**
 * Check if a given object implements the Language interface.
 */
export function instanceOfLanguage(value: object): value is Language {
  return true;
}

export function LanguageFromJSON(json: any): Language {
  return LanguageFromJSONTyped(json, false);
}

export function LanguageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Language {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    inspire: json['inspire'] == null ? undefined : json['inspire'],
    inspireJPAWorkaround:
      json['inspire_JPAWorkaround'] == null
        ? undefined
        : json['inspire_JPAWorkaround'],
    name: json['name'] == null ? undefined : json['name'],
  };
}

export function LanguageToJSON(value?: Language | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    inspire: value['inspire'],
    inspire_JPAWorkaround: value['inspireJPAWorkaround'],
    name: value['name'],
  };
}
