/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Identifier template details
 * @export
 * @interface MetadataIdentifierTemplate
 */
export interface MetadataIdentifierTemplate {
  /**
   *
   * @type {number}
   * @memberof MetadataIdentifierTemplate
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifierTemplate
   */
  name?: string;
  /**
   *
   * @type {boolean}
   * @memberof MetadataIdentifierTemplate
   */
  systemDefault?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MetadataIdentifierTemplate
   */
  systemProvided?: boolean;
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifierTemplate
   */
  systemProvidedJPAWorkaround?: string;
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifierTemplate
   */
  template?: string;
}

/**
 * Check if a given object implements the MetadataIdentifierTemplate interface.
 */
export function instanceOfMetadataIdentifierTemplate(
  value: object
): value is MetadataIdentifierTemplate {
  return true;
}

export function MetadataIdentifierTemplateFromJSON(
  json: any
): MetadataIdentifierTemplate {
  return MetadataIdentifierTemplateFromJSONTyped(json, false);
}

export function MetadataIdentifierTemplateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MetadataIdentifierTemplate {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    systemDefault:
      json['systemDefault'] == null ? undefined : json['systemDefault'],
    systemProvided:
      json['systemProvided'] == null ? undefined : json['systemProvided'],
    systemProvidedJPAWorkaround:
      json['systemProvided_JPAWorkaround'] == null
        ? undefined
        : json['systemProvided_JPAWorkaround'],
    template: json['template'] == null ? undefined : json['template'],
  };
}

export function MetadataIdentifierTemplateToJSON(
  value?: MetadataIdentifierTemplate | null
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    name: value['name'],
    systemDefault: value['systemDefault'],
    systemProvided: value['systemProvided'],
    systemProvided_JPAWorkaround: value['systemProvidedJPAWorkaround'],
    template: value['template'],
  };
}
