/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata status
 * @export
 * @interface MetadataStatusParameter
 */
export interface MetadataStatusParameter {
  /**
   *
   * @type {string}
   * @memberof MetadataStatusParameter
   */
  changeMessage?: string;
  /**
   *
   * @type {string}
   * @memberof MetadataStatusParameter
   */
  closeDate?: string;
  /**
   *
   * @type {string}
   * @memberof MetadataStatusParameter
   */
  dueDate?: string;
  /**
   *
   * @type {number}
   * @memberof MetadataStatusParameter
   */
  owner?: number;
  /**
   *
   * @type {number}
   * @memberof MetadataStatusParameter
   */
  status?: number;
  /**
   *
   * @type {string}
   * @memberof MetadataStatusParameter
   */
  type?: MetadataStatusParameterTypeEnum;
}

/**
 * @export
 */
export const MetadataStatusParameterTypeEnum = {
  Workflow: 'workflow',
  Task: 'task',
  Event: 'event',
} as const;
export type MetadataStatusParameterTypeEnum =
  (typeof MetadataStatusParameterTypeEnum)[keyof typeof MetadataStatusParameterTypeEnum];

/**
 * Check if a given object implements the MetadataStatusParameter interface.
 */
export function instanceOfMetadataStatusParameter(
  value: object
): value is MetadataStatusParameter {
  return true;
}

export function MetadataStatusParameterFromJSON(
  json: any
): MetadataStatusParameter {
  return MetadataStatusParameterFromJSONTyped(json, false);
}

export function MetadataStatusParameterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MetadataStatusParameter {
  if (json == null) {
    return json;
  }
  return {
    changeMessage:
      json['changeMessage'] == null ? undefined : json['changeMessage'],
    closeDate: json['closeDate'] == null ? undefined : json['closeDate'],
    dueDate: json['dueDate'] == null ? undefined : json['dueDate'],
    owner: json['owner'] == null ? undefined : json['owner'],
    status: json['status'] == null ? undefined : json['status'],
    type: json['type'] == null ? undefined : json['type'],
  };
}

export function MetadataStatusParameterToJSON(
  value?: MetadataStatusParameter | null
): any {
  if (value == null) {
    return value;
  }
  return {
    changeMessage: value['changeMessage'],
    closeDate: value['closeDate'],
    dueDate: value['dueDate'],
    owner: value['owner'],
    status: value['status'],
    type: value['type'],
  };
}
