/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PasswordResetDto
 */
export interface PasswordResetDto {
  /**
   *
   * @type {string}
   * @memberof PasswordResetDto
   */
  password?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResetDto
   */
  password2?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordResetDto
   */
  passwordOld?: string;
}

/**
 * Check if a given object implements the PasswordResetDto interface.
 */
export function instanceOfPasswordResetDto(
  value: object
): value is PasswordResetDto {
  return true;
}

export function PasswordResetDtoFromJSON(json: any): PasswordResetDto {
  return PasswordResetDtoFromJSONTyped(json, false);
}

export function PasswordResetDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PasswordResetDto {
  if (json == null) {
    return json;
  }
  return {
    password: json['password'] == null ? undefined : json['password'],
    password2: json['password2'] == null ? undefined : json['password2'],
    passwordOld: json['passwordOld'] == null ? undefined : json['passwordOld'],
  };
}

export function PasswordResetDtoToJSON(value?: PasswordResetDto | null): any {
  if (value == null) {
    return value;
  }
  return {
    password: value['password'],
    password2: value['password2'],
    passwordOld: value['passwordOld'],
  };
}
