/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PutResourceRequest
 */
export interface PutResourceRequest {
  /**
   * The file to upload
   * @type {Blob}
   * @memberof PutResourceRequest
   */
  file: Blob;
}

/**
 * Check if a given object implements the PutResourceRequest interface.
 */
export function instanceOfPutResourceRequest(
  value: object
): value is PutResourceRequest {
  if (!('file' in value) || value['file'] === undefined) return false;
  return true;
}

export function PutResourceRequestFromJSON(json: any): PutResourceRequest {
  return PutResourceRequestFromJSONTyped(json, false);
}

export function PutResourceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PutResourceRequest {
  if (json == null) {
    return json;
  }
  return {
    file: json['file'],
  };
}

export function PutResourceRequestToJSON(
  value?: PutResourceRequest | null
): any {
  if (value == null) {
    return value;
  }
  return {
    file: value['file'],
  };
}
