/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RatingAverage
 */
export interface RatingAverage {
  /**
   *
   * @type {string}
   * @memberof RatingAverage
   */
  lastComment?: string;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof RatingAverage
   */
  ratingAverages?: { [key: string]: number };
  /**
   *
   * @type {number}
   * @memberof RatingAverage
   */
  ratingCount?: number;
  /**
   *
   * @type {number}
   * @memberof RatingAverage
   */
  userfeedbackCount?: number;
}

/**
 * Check if a given object implements the RatingAverage interface.
 */
export function instanceOfRatingAverage(value: object): value is RatingAverage {
  return true;
}

export function RatingAverageFromJSON(json: any): RatingAverage {
  return RatingAverageFromJSONTyped(json, false);
}

export function RatingAverageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RatingAverage {
  if (json == null) {
    return json;
  }
  return {
    lastComment: json['lastComment'] == null ? undefined : json['lastComment'],
    ratingAverages:
      json['ratingAverages'] == null ? undefined : json['ratingAverages'],
    ratingCount: json['ratingCount'] == null ? undefined : json['ratingCount'],
    userfeedbackCount:
      json['userfeedbackCount'] == null ? undefined : json['userfeedbackCount'],
  };
}

export function RatingAverageToJSON(value?: RatingAverage | null): any {
  if (value == null) {
    return value;
  }
  return {
    lastComment: value['lastComment'],
    ratingAverages: value['ratingAverages'],
    ratingCount: value['ratingCount'],
    userfeedbackCount: value['userfeedbackCount'],
  };
}
