/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultilingualValue } from './MultilingualValue';
import {
  MultilingualValueFromJSON,
  MultilingualValueFromJSONTyped,
  MultilingualValueToJSON,
} from './MultilingualValue';

/**
 *
 * @export
 * @interface RelatedThumbnailItem
 */
export interface RelatedThumbnailItem {
  /**
   *
   * @type {string}
   * @memberof RelatedThumbnailItem
   */
  hash?: string;
  /**
   *
   * @type {string}
   * @memberof RelatedThumbnailItem
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof RelatedThumbnailItem
   */
  idx?: string;
  /**
   *
   * @type {MultilingualValue}
   * @memberof RelatedThumbnailItem
   */
  title: MultilingualValue;
  /**
   *
   * @type {string}
   * @memberof RelatedThumbnailItem
   */
  type?: string;
  /**
   *
   * @type {MultilingualValue}
   * @memberof RelatedThumbnailItem
   */
  url?: MultilingualValue;
}

/**
 * Check if a given object implements the RelatedThumbnailItem interface.
 */
export function instanceOfRelatedThumbnailItem(
  value: object
): value is RelatedThumbnailItem {
  if (!('title' in value) || value['title'] === undefined) return false;
  return true;
}

export function RelatedThumbnailItemFromJSON(json: any): RelatedThumbnailItem {
  return RelatedThumbnailItemFromJSONTyped(json, false);
}

export function RelatedThumbnailItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RelatedThumbnailItem {
  if (json == null) {
    return json;
  }
  return {
    hash: json['hash'] == null ? undefined : json['hash'],
    id: json['id'] == null ? undefined : json['id'],
    idx: json['idx'] == null ? undefined : json['idx'],
    title: MultilingualValueFromJSON(json['title']),
    type: json['type'] == null ? undefined : json['type'],
    url:
      json['url'] == null ? undefined : MultilingualValueFromJSON(json['url']),
  };
}

export function RelatedThumbnailItemToJSON(
  value?: RelatedThumbnailItem | null
): any {
  if (value == null) {
    return value;
  }
  return {
    hash: value['hash'],
    id: value['id'],
    idx: value['idx'],
    title: MultilingualValueToJSON(value['title']),
    type: value['type'],
    url: MultilingualValueToJSON(value['url']),
  };
}
