/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelatedMetadataItem } from './RelatedMetadataItem';
import {
  RelatedMetadataItemFromJSON,
  RelatedMetadataItemFromJSONTyped,
  RelatedMetadataItemToJSON,
} from './RelatedMetadataItem';

/**
 *
 * @export
 * @interface Related
 */
export interface Related {
  /**
   *
   * @type {Array<RelatedMetadataItem>}
   * @memberof Related
   */
  item?: Array<RelatedMetadataItem>;
}

/**
 * Check if a given object implements the Related interface.
 */
export function instanceOfRelated(value: object): value is Related {
  return true;
}

export function RelatedFromJSON(json: any): Related {
  return RelatedFromJSONTyped(json, false);
}

export function RelatedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Related {
  if (json == null) {
    return json;
  }
  return {
    item:
      json['item'] == null
        ? undefined
        : (json['item'] as Array<any>).map(RelatedMetadataItemFromJSON),
  };
}

export function RelatedToJSON(value?: Related | null): any {
  if (value == null) {
    return value;
  }
  return {
    item:
      value['item'] == null
        ? undefined
        : (value['item'] as Array<any>).map(RelatedMetadataItemToJSON),
  };
}
