/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationReport } from './ValidationReport';
import {
  ValidationReportFromJSON,
  ValidationReportFromJSONTyped,
  ValidationReportToJSON,
} from './ValidationReport';

/**
 *
 * @export
 * @interface Reports
 */
export interface Reports {
  /**
   *
   * @type {Array<ValidationReport>}
   * @memberof Reports
   */
  report?: Array<ValidationReport>;
}

/**
 * Check if a given object implements the Reports interface.
 */
export function instanceOfReports(value: object): value is Reports {
  return true;
}

export function ReportsFromJSON(json: any): Reports {
  return ReportsFromJSONTyped(json, false);
}

export function ReportsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Reports {
  if (json == null) {
    return json;
  }
  return {
    report:
      json['report'] == null
        ? undefined
        : (json['report'] as Array<any>).map(ValidationReportFromJSON),
  };
}

export function ReportsToJSON(value?: Reports | null): any {
  if (value == null) {
    return value;
  }
  return {
    report:
      value['report'] == null
        ? undefined
        : (value['report'] as Array<any>).map(ValidationReportToJSON),
  };
}
