/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Field } from './Field';
import { FieldFromJSON, FieldFromJSONTyped, FieldToJSON } from './Field';

/**
 *
 * @export
 * @interface Section
 */
export interface Section {
  /**
   *
   * @type {Array<Field>}
   * @memberof Section
   */
  field: Array<Field>;
  /**
   *
   * @type {string}
   * @memberof Section
   */
  name?: string;
}

/**
 * Check if a given object implements the Section interface.
 */
export function instanceOfSection(value: object): value is Section {
  if (!('field' in value) || value['field'] === undefined) return false;
  return true;
}

export function SectionFromJSON(json: any): Section {
  return SectionFromJSONTyped(json, false);
}

export function SectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Section {
  if (json == null) {
    return json;
  }
  return {
    field: (json['field'] as Array<any>).map(FieldFromJSON),
    name: json['name'] == null ? undefined : json['name'],
  };
}

export function SectionToJSON(value?: Section | null): any {
  if (value == null) {
    return value;
  }
  return {
    field: (value['field'] as Array<any>).map(FieldToJSON),
    name: value['name'],
  };
}
