/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Selection
 */
export interface Selection {
  /**
   *
   * @type {number}
   * @memberof Selection
   */
  id?: number;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof Selection
   */
  label?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof Selection
   */
  name?: string;
  /**
   *
   * @type {boolean}
   * @memberof Selection
   */
  watchable?: boolean;
}

/**
 * Check if a given object implements the Selection interface.
 */
export function instanceOfSelection(value: object): value is Selection {
  return true;
}

export function SelectionFromJSON(json: any): Selection {
  return SelectionFromJSONTyped(json, false);
}

export function SelectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Selection {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'] == null ? undefined : json['name'],
    watchable: json['watchable'] == null ? undefined : json['watchable'],
  };
}

export function SelectionToJSON(value?: Selection | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    label: value['label'],
    name: value['name'],
    watchable: value['watchable'],
  };
}
