/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Report } from './Report';
import { ReportFromJSON, ReportFromJSONTyped, ReportToJSON } from './Report';
import type { InfoReport } from './InfoReport';
import {
  InfoReportFromJSON,
  InfoReportFromJSONTyped,
  InfoReportToJSON,
} from './InfoReport';

/**
 *
 * @export
 * @interface SimpleMetadataProcessingReport
 */
export interface SimpleMetadataProcessingReport {
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  ellapsedTimeInSeconds?: number;
  /**
   *
   * @type {string}
   * @memberof SimpleMetadataProcessingReport
   */
  endIsoDateTime?: string;
  /**
   *
   * @type {Array<Report>}
   * @memberof SimpleMetadataProcessingReport
   */
  errors?: Array<Report>;
  /**
   *
   * @type {Array<InfoReport>}
   * @memberof SimpleMetadataProcessingReport
   */
  infos?: Array<InfoReport>;
  /**
   *
   * @type {Set<number>}
   * @memberof SimpleMetadataProcessingReport
   */
  metadata?: Set<number>;
  /**
   *
   * @type {{ [key: string]: Array<Report>; }}
   * @memberof SimpleMetadataProcessingReport
   */
  metadataErrors?: { [key: string]: Array<Report> };
  /**
   *
   * @type {{ [key: string]: Array<InfoReport>; }}
   * @memberof SimpleMetadataProcessingReport
   */
  metadataInfos?: { [key: string]: Array<InfoReport> };
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfNullRecords?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfRecordNotFound?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfRecords?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfRecordsNotEditable?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfRecordsProcessed?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfRecordsUnchanged?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  numberOfRecordsWithErrors?: number;
  /**
   *
   * @type {boolean}
   * @memberof SimpleMetadataProcessingReport
   */
  running?: boolean;
  /**
   *
   * @type {string}
   * @memberof SimpleMetadataProcessingReport
   */
  startIsoDateTime?: string;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  totalRecords?: number;
  /**
   *
   * @type {number}
   * @memberof SimpleMetadataProcessingReport
   */
  totalTimeInSeconds?: number;
  /**
   *
   * @type {string}
   * @memberof SimpleMetadataProcessingReport
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof SimpleMetadataProcessingReport
   */
  uuid?: string;
}

/**
 * Check if a given object implements the SimpleMetadataProcessingReport interface.
 */
export function instanceOfSimpleMetadataProcessingReport(
  value: object
): value is SimpleMetadataProcessingReport {
  return true;
}

export function SimpleMetadataProcessingReportFromJSON(
  json: any
): SimpleMetadataProcessingReport {
  return SimpleMetadataProcessingReportFromJSONTyped(json, false);
}

export function SimpleMetadataProcessingReportFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SimpleMetadataProcessingReport {
  if (json == null) {
    return json;
  }
  return {
    ellapsedTimeInSeconds:
      json['ellapsedTimeInSeconds'] == null
        ? undefined
        : json['ellapsedTimeInSeconds'],
    endIsoDateTime:
      json['endIsoDateTime'] == null ? undefined : json['endIsoDateTime'],
    errors:
      json['errors'] == null
        ? undefined
        : (json['errors'] as Array<any>).map(ReportFromJSON),
    infos:
      json['infos'] == null
        ? undefined
        : (json['infos'] as Array<any>).map(InfoReportFromJSON),
    metadata: json['metadata'] == null ? undefined : json['metadata'],
    metadataErrors:
      json['metadataErrors'] == null ? undefined : json['metadataErrors'],
    metadataInfos:
      json['metadataInfos'] == null ? undefined : json['metadataInfos'],
    numberOfNullRecords:
      json['numberOfNullRecords'] == null
        ? undefined
        : json['numberOfNullRecords'],
    numberOfRecordNotFound:
      json['numberOfRecordNotFound'] == null
        ? undefined
        : json['numberOfRecordNotFound'],
    numberOfRecords:
      json['numberOfRecords'] == null ? undefined : json['numberOfRecords'],
    numberOfRecordsNotEditable:
      json['numberOfRecordsNotEditable'] == null
        ? undefined
        : json['numberOfRecordsNotEditable'],
    numberOfRecordsProcessed:
      json['numberOfRecordsProcessed'] == null
        ? undefined
        : json['numberOfRecordsProcessed'],
    numberOfRecordsUnchanged:
      json['numberOfRecordsUnchanged'] == null
        ? undefined
        : json['numberOfRecordsUnchanged'],
    numberOfRecordsWithErrors:
      json['numberOfRecordsWithErrors'] == null
        ? undefined
        : json['numberOfRecordsWithErrors'],
    running: json['running'] == null ? undefined : json['running'],
    startIsoDateTime:
      json['startIsoDateTime'] == null ? undefined : json['startIsoDateTime'],
    totalRecords:
      json['totalRecords'] == null ? undefined : json['totalRecords'],
    totalTimeInSeconds:
      json['totalTimeInSeconds'] == null
        ? undefined
        : json['totalTimeInSeconds'],
    type: json['type'] == null ? undefined : json['type'],
    uuid: json['uuid'] == null ? undefined : json['uuid'],
  };
}

export function SimpleMetadataProcessingReportToJSON(
  value?: SimpleMetadataProcessingReport | null
): any {
  if (value == null) {
    return value;
  }
  return {
    ellapsedTimeInSeconds: value['ellapsedTimeInSeconds'],
    endIsoDateTime: value['endIsoDateTime'],
    errors:
      value['errors'] == null
        ? undefined
        : (value['errors'] as Array<any>).map(ReportToJSON),
    infos:
      value['infos'] == null
        ? undefined
        : (value['infos'] as Array<any>).map(InfoReportToJSON),
    metadata:
      value['metadata'] == null
        ? undefined
        : Array.from(value['metadata'] as Set<any>),
    metadataErrors: value['metadataErrors'],
    metadataInfos: value['metadataInfos'],
    numberOfNullRecords: value['numberOfNullRecords'],
    numberOfRecordNotFound: value['numberOfRecordNotFound'],
    numberOfRecords: value['numberOfRecords'],
    numberOfRecordsNotEditable: value['numberOfRecordsNotEditable'],
    numberOfRecordsProcessed: value['numberOfRecordsProcessed'],
    numberOfRecordsUnchanged: value['numberOfRecordsUnchanged'],
    numberOfRecordsWithErrors: value['numberOfRecordsWithErrors'],
    running: value['running'],
    startIsoDateTime: value['startIsoDateTime'],
    totalRecords: value['totalRecords'],
    totalTimeInSeconds: value['totalTimeInSeconds'],
    type: value['type'],
    uuid: value['uuid'],
  };
}
