/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Translations
 */
export interface Translations {
  /**
   *
   * @type {string}
   * @memberof Translations
   */
  fieldName?: string;
  /**
   *
   * @type {number}
   * @memberof Translations
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Translations
   */
  langId?: string;
  /**
   *
   * @type {string}
   * @memberof Translations
   */
  value?: string;
}

/**
 * Check if a given object implements the Translations interface.
 */
export function instanceOfTranslations(value: object): value is Translations {
  return true;
}

export function TranslationsFromJSON(json: any): Translations {
  return TranslationsFromJSONTyped(json, false);
}

export function TranslationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Translations {
  if (json == null) {
    return json;
  }
  return {
    fieldName: json['fieldName'] == null ? undefined : json['fieldName'],
    id: json['id'] == null ? undefined : json['id'],
    langId: json['langId'] == null ? undefined : json['langId'],
    value: json['value'] == null ? undefined : json['value'],
  };
}

export function TranslationsToJSON(value?: Translations | null): any {
  if (value == null) {
    return value;
  }
  return {
    fieldName: value['fieldName'],
    id: value['id'],
    langId: value['langId'],
    value: value['value'],
  };
}
