/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UiSetting
 */
export interface UiSetting {
  /**
   *
   * @type {string}
   * @memberof UiSetting
   */
  _configuration?: string;
  /**
   *
   * @type {string}
   * @memberof UiSetting
   */
  id?: string;
}

/**
 * Check if a given object implements the UiSetting interface.
 */
export function instanceOfUiSetting(value: object): value is UiSetting {
  return true;
}

export function UiSettingFromJSON(json: any): UiSetting {
  return UiSettingFromJSONTyped(json, false);
}

export function UiSettingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UiSetting {
  if (json == null) {
    return json;
  }
  return {
    _configuration:
      json['configuration'] == null ? undefined : json['configuration'],
    id: json['id'] == null ? undefined : json['id'],
  };
}

export function UiSettingToJSON(value?: UiSetting | null): any {
  if (value == null) {
    return value;
  }
  return {
    configuration: value['_configuration'],
    id: value['id'],
  };
}
