/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User search details
 * @export
 * @interface UserSearchDto
 */
export interface UserSearchDto {
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  creationDate?: string;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  creator?: string;
  /**
   *
   * @type {number}
   * @memberof UserSearchDto
   */
  creatorId?: number;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  featuredType?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof UserSearchDto
   */
  groups?: Array<number>;
  /**
   *
   * @type {number}
   * @memberof UserSearchDto
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  logo?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof UserSearchDto
   */
  names?: { [key: string]: string };
  /**
   *
   * @type {string}
   * @memberof UserSearchDto
   */
  url?: string;
}

/**
 * Check if a given object implements the UserSearchDto interface.
 */
export function instanceOfUserSearchDto(value: object): value is UserSearchDto {
  return true;
}

export function UserSearchDtoFromJSON(json: any): UserSearchDto {
  return UserSearchDtoFromJSONTyped(json, false);
}

export function UserSearchDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserSearchDto {
  if (json == null) {
    return json;
  }
  return {
    creationDate:
      json['creationDate'] == null ? undefined : json['creationDate'],
    creator: json['creator'] == null ? undefined : json['creator'],
    creatorId: json['creatorId'] == null ? undefined : json['creatorId'],
    featuredType:
      json['featuredType'] == null ? undefined : json['featuredType'],
    groups: json['groups'] == null ? undefined : json['groups'],
    id: json['id'] == null ? undefined : json['id'],
    logo: json['logo'] == null ? undefined : json['logo'],
    names: json['names'] == null ? undefined : json['names'],
    url: json['url'] == null ? undefined : json['url'],
  };
}

export function UserSearchDtoToJSON(value?: UserSearchDto | null): any {
  if (value == null) {
    return value;
  }
  return {
    creationDate: value['creationDate'],
    creator: value['creator'],
    creatorId: value['creatorId'],
    featuredType: value['featuredType'],
    groups: value['groups'],
    id: value['id'],
    logo: value['logo'],
    names: value['names'],
    url: value['url'],
  };
}
