/*
 * (c) 2003 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license,
 * available at the root application directory.
 */
package org.geonetwork.index.model.record;

import static com.fasterxml.jackson.databind.DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS;
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

/**
 * Very simple test to ensure that the two different formats `isPublishedTo*` for published vs unpublished properly
 * parse.
 *
 * <p>"isPublishedToAll": "true"
 *
 * <p>"isPublishedToAll": [ true ]
 */
public class IndexRecordPublishFormatTest {

    String json = "{\n" + "    \"docType\": \"metadata\",\n"
            + "    \"document\": \"\",\n"
            + "    \"metadataIdentifier\": \"ce6dc729-7ec0-4ba9-baf8-4bc1525120c8\",\n"
            + "    \"standardNameObject\": {\n"
            + "      \"default\": \"ISO 19115:2003/19139\",\n"
            + "      \"langeng\": \"ISO 19115:2003/19139\"\n"
            + "    },\n"
            + "    \"standardVersionObject\": {\n"
            + "      \"default\": \"1.0\",\n"
            + "      \"langeng\": \"1.0\"\n"
            + "    },\n"
            + "    \"resourceTypeNameObject\": {\n"
            + "      \"default\": \"service - distributed Z23950 zservice\",\n"
            + "      \"langeng\": \"service - distributed Z23950 zservice\"\n"
            + "    },\n"
            + "    \"indexingDate\": \"2025-01-13T13:44:41-08:00\",\n"
            + "    \"dateStamp\": \"2009-10-15T07:00:00.000Z\",\n"
            + "    \"mainLanguage\": \"eng\",\n"
            + "    \"resourceType\": [\n"
            + "      \"service\"\n"
            + "    ],\n"
            + "    \"OrgObject\": {\n"
            + "      \"default\": \"Geoffrey's Tube Australia\",\n"
            + "      \"langeng\": \"Geoffrey's Tube Australia\"\n"
            + "    },\n"
            + "    \"resourceProviderOrgObject\": {\n"
            + "      \"default\": \"Geoffrey's Tube Australia\",\n"
            + "      \"langeng\": \"Geoffrey's Tube Australia\"\n"
            + "    },\n"
            + "    \"contact\": [\n"
            + "      {\n"
            + "        \"organisationObject\": {\n"
            + "          \"default\": \"Geoffrey's Tube Australia\",\n"
            + "          \"langeng\": \"Geoffrey's Tube Australia\"\n"
            + "        },\n"
            + "        \"role\": \"resourceProvider\",\n"
            + "        \"email\": \"\",\n"
            + "        \"website\": \"\",\n"
            + "        \"logo\": \"\",\n"
            + "        \"individual\": \"\",\n"
            + "        \"position\": \"\",\n"
            + "        \"phone\": \"\",\n"
            + "        \"address\": \"\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"cl_hierarchyLevel\": [\n"
            + "      {\n"
            + "        \"key\": \"service\",\n"
            + "        \"default\": \"Service\",\n"
            + "        \"langeng\": \"Service\",\n"
            + "        \"link\": \"http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#MD_ScopeCode\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"cl_function\": [\n"
            + "      {\n"
            + "        \"key\": \"search\",\n"
            + "        \"default\": \"Search\",\n"
            + "        \"langeng\": \"Search\",\n"
            + "        \"link\": \"http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#CI_OnLineFunctionCode\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"resourceTitleObject\": {\n"
            + "      \"default\": \"The Geoffrey's Tube Z3950 Server (Sample Record - Please Delete!)\",\n"
            + "      \"langeng\": \"The Geoffrey's Tube Z3950 Server (Sample Record - Please Delete!)\"\n"
            + "    },\n"
            + "    \"revisionDateForResource\": [\n"
            + "      \"2010-03-24\"\n"
            + "    ],\n"
            + "    \"revisionYearForResource\": \"2010\",\n"
            + "    \"revisionMonthForResource\": \"2010-03\",\n"
            + "    \"resourceDate\": [\n"
            + "      {\n"
            + "        \"type\": \"revision\",\n"
            + "        \"date\": \"2010-03-24T07:00:00.000Z\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"resourceTemporalDateRange\": [\n"
            + "      {\n"
            + "        \"gte\": \"2010-03-24T07:00:00.000Z\",\n"
            + "        \"lte\": \"2010-03-24T07:00:00.000Z\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"resourceAbstractObject\": {\n"
            + "      \"default\": \"This catalog is for registering all metadata records held by the Geofffrey's Tube Palace Hotel Ballroom.\",\n"
            + "      \"langeng\": \"This catalog is for registering all metadata records held by the Geofffrey's Tube Palace Hotel Ballroom.\"\n"
            + "    },\n"
            + "    \"hasOverview\": \"false\",\n"
            + "    \"tag\": [],\n"
            + "    \"tagNumber\": \"0\",\n"
            + "    \"isOpenData\": \"false\",\n"
            + "    \"allKeywords\": {},\n"
            + "    \"geom\": [\n"
            + "      {\n"
            + "        \"type\": \"Polygon\",\n"
            + "        \"coordinates\": [\n"
            + "          [\n"
            + "            [\n"
            + "              112,\n"
            + "              -44\n"
            + "            ],\n"
            + "            [\n"
            + "              154,\n"
            + "              -44\n"
            + "            ],\n"
            + "            [\n"
            + "              154,\n"
            + "              -9\n"
            + "            ],\n"
            + "            [\n"
            + "              112,\n"
            + "              -9\n"
            + "            ],\n"
            + "            [\n"
            + "              112,\n"
            + "              -44\n"
            + "            ]\n"
            + "          ]\n"
            + "        ]\n"
            + "      }\n"
            + "    ],\n"
            + "    \"location\": \"-26.5,133\",\n"
            + "    \"serviceType\": \"ISO 23950 gateway\",\n"
            + "    \"recordGroup\": \"ce6dc729-7ec0-4ba9-baf8-4bc1525120c8\",\n"
            + "    \"recordOwner\": \"admin admin\",\n"
            + "    \"uuid\": \"ce6dc729-7ec0-4ba9-baf8-4bc1525120c8\",\n"
            + "    \"displayOrder\": \"0\",\n"
            + "    \"groupPublishedId\": [\n"
            + "      \"2\",\n"
            + "      \"1\",\n"
            + "      \"0\"\n"
            + "    ],\n"
            + "    \"popularity\": \"1\",\n"
            + "    \"userinfo\": \"admin|admin|admin|Administrator\",\n"
            + "    \"groupPublished\": [\n"
            + "      \"sample\",\n"
            + "      \"all\",\n"
            + "      \"intranet\"\n"
            + "    ],\n"
            + "    \"isPublishedToAll\": \"true\",\n"
            + "    \"record\": \"record\",\n"
            + "    \"cat\": [\n"
            + "      \"datasets\"\n"
            + "    ],\n"
            + "    \"draft\": \"n\",\n"
            + "    \"changeDate\": \"2010-02-02T08:00:00Z\",\n"
            + "    \"id\": \"104\",\n"
            + "    \"createDate\": \"2010-02-02T08:00:00Z\",\n"
            + "    \"isPublishedToIntranet\": \"true\",\n"
            + "    \"owner\": \"1\",\n"
            + "    \"logo\": \"/images/logos/7d436f18-8b38-42a4-8df7-1fd0fbaafc8f.png\",\n"
            + "    \"hasxlinks\": \"false\",\n"
            + "    \"op0\": [\n"
            + "      \"2\",\n"
            + "      \"1\",\n"
            + "      \"0\"\n"
            + "    ],\n"
            + "    \"featureOfRecord\": \"record\",\n"
            + "    \"op1\": [\n"
            + "      \"2\",\n"
            + "      \"1\",\n"
            + "      \"0\"\n"
            + "    ],\n"
            + "    \"isPublishedToGuest\": \"false\",\n"
            + "    \"extra\": \"null\",\n"
            + "    \"documentStandard\": \"iso19139\",\n"
            + "    \"op3\": [\n"
            + "      \"2\",\n"
            + "      \"1\"\n"
            + "    ],\n"
            + "    \"op6\": [\n"
            + "      \"0\",\n"
            + "      \"1\",\n"
            + "      \"2\"\n"
            + "    ],\n"
            + "    \"op5\": [\n"
            + "      \"2\",\n"
            + "      \"1\",\n"
            + "      \"0\"\n"
            + "    ],\n"
            + "    \"valid\": \"-1\",\n"
            + "    \"isTemplate\": \"n\",\n"
            + "    \"feedbackCount\": \"0\",\n"
            + "    \"rating\": \"0\",\n"
            + "    \"isHarvested\": \"false\",\n"
            + "    \"userSavedCount\": \"0\",\n"
            + "    \"sourceCatalogue\": \"7d436f18-8b38-42a4-8df7-1fd0fbaafc8f\"\n"
            + "  }\n";

    String json2 = " {\n" + "    \"docType\": \"metadata\",\n"
            + "    \"document\": \"\",\n"
            + "    \"metadataIdentifier\": \"ce6dc729-7ec0-4ba9-baf8-4bc1525120c8\",\n"
            + "    \"standardNameObject\": {\n"
            + "      \"default\": \"ISO 19115:2003/19139\",\n"
            + "      \"langeng\": \"ISO 19115:2003/19139\"\n"
            + "    },\n"
            + "    \"standardVersionObject\": {\n"
            + "      \"default\": \"1.0\",\n"
            + "      \"langeng\": \"1.0\"\n"
            + "    },\n"
            + "    \"resourceTypeNameObject\": {\n"
            + "      \"default\": \"service - distributed Z23950 zservice\",\n"
            + "      \"langeng\": \"service - distributed Z23950 zservice\"\n"
            + "    },\n"
            + "    \"indexingDate\": 1736805518301,\n"
            + "    \"dateStamp\": \"2009-10-15T07:00:00.000Z\",\n"
            + "    \"mainLanguage\": \"eng\",\n"
            + "    \"resourceType\": [\n"
            + "      \"service\"\n"
            + "    ],\n"
            + "    \"OrgObject\": {\n"
            + "      \"default\": \"Geoffrey's Tube Australia\",\n"
            + "      \"langeng\": \"Geoffrey's Tube Australia\"\n"
            + "    },\n"
            + "    \"resourceProviderOrgObject\": {\n"
            + "      \"default\": \"Geoffrey's Tube Australia\",\n"
            + "      \"langeng\": \"Geoffrey's Tube Australia\"\n"
            + "    },\n"
            + "    \"contact\": [\n"
            + "      {\n"
            + "        \"organisationObject\": {\n"
            + "          \"default\": \"Geoffrey's Tube Australia\",\n"
            + "          \"langeng\": \"Geoffrey's Tube Australia\"\n"
            + "        },\n"
            + "        \"role\": \"resourceProvider\",\n"
            + "        \"email\": \"\",\n"
            + "        \"website\": \"\",\n"
            + "        \"logo\": \"\",\n"
            + "        \"individual\": \"\",\n"
            + "        \"position\": \"\",\n"
            + "        \"phone\": \"\",\n"
            + "        \"address\": \"\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"cl_hierarchyLevel\": [\n"
            + "      {\n"
            + "        \"key\": \"service\",\n"
            + "        \"default\": \"Service\",\n"
            + "        \"langeng\": \"Service\",\n"
            + "        \"link\": \"http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#MD_ScopeCode\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"cl_function\": [\n"
            + "      {\n"
            + "        \"key\": \"search\",\n"
            + "        \"default\": \"Search\",\n"
            + "        \"langeng\": \"Search\",\n"
            + "        \"link\": \"http://asdd.ga.gov.au/asdd/profileinfo/gmxCodelists.xml#CI_OnLineFunctionCode\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"resourceTitleObject\": {\n"
            + "      \"default\": \"The Geoffrey's Tube Z3950 Server (Sample Record - Please Delete!)\",\n"
            + "      \"langeng\": \"The Geoffrey's Tube Z3950 Server (Sample Record - Please Delete!)\"\n"
            + "    },\n"
            + "    \"revisionDateForResource\": [\n"
            + "      \"2010-03-24\"\n"
            + "    ],\n"
            + "    \"revisionYearForResource\": \"2010\",\n"
            + "    \"revisionMonthForResource\": \"2010-03\",\n"
            + "    \"resourceDate\": [\n"
            + "      {\n"
            + "        \"type\": \"revision\",\n"
            + "        \"date\": \"2010-03-24T07:00:00.000Z\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"resourceTemporalDateRange\": [\n"
            + "      {\n"
            + "        \"gte\": \"2010-03-24T07:00:00.000Z\",\n"
            + "        \"lte\": \"2010-03-24T07:00:00.000Z\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"resourceAbstractObject\": {\n"
            + "      \"default\": \"This catalog is for registering all metadata records held by the Geofffrey's Tube Palace Hotel Ballroom.\",\n"
            + "      \"langeng\": \"This catalog is for registering all metadata records held by the Geofffrey's Tube Palace Hotel Ballroom.\"\n"
            + "    },\n"
            + "    \"hasOverview\": \"false\",\n"
            + "    \"tag\": [],\n"
            + "    \"tagNumber\": \"0\",\n"
            + "    \"isOpenData\": \"false\",\n"
            + "    \"allKeywords\": {},\n"
            + "    \"geom\": [\n"
            + "      {\n"
            + "        \"type\": \"Polygon\",\n"
            + "        \"coordinates\": [\n"
            + "          [\n"
            + "            [\n"
            + "              112,\n"
            + "              -44\n"
            + "            ],\n"
            + "            [\n"
            + "              154,\n"
            + "              -44\n"
            + "            ],\n"
            + "            [\n"
            + "              154,\n"
            + "              -9\n"
            + "            ],\n"
            + "            [\n"
            + "              112,\n"
            + "              -9\n"
            + "            ],\n"
            + "            [\n"
            + "              112,\n"
            + "              -44\n"
            + "            ]\n"
            + "          ]\n"
            + "        ]\n"
            + "      }\n"
            + "    ],\n"
            + "    \"location\": \"-26.5,133\",\n"
            + "    \"serviceType\": \"ISO 23950 gateway\",\n"
            + "    \"recordGroup\": \"ce6dc729-7ec0-4ba9-baf8-4bc1525120c8\",\n"
            + "    \"recordOwner\": \"admin admin\",\n"
            + "    \"uuid\": \"ce6dc729-7ec0-4ba9-baf8-4bc1525120c8\",\n"
            + "    \"displayOrder\": \"0\",\n"
            + "    \"groupPublishedId\": [\n"
            + "      2,\n"
            + "      1\n"
            + "    ],\n"
            + "    \"popularity\": \"1\",\n"
            + "    \"userinfo\": \"admin|admin|admin|Administrator\",\n"
            + "    \"groupPublished\": [\n"
            + "      \"sample\",\n"
            + "      \"all\"\n"
            + "    ],\n"
            + "    \"isPublishedToAll\": [\n"
            + "      true\n"
            + "    ],\n"
            + "    \"record\": \"record\",\n"
            + "    \"cat\": [\n"
            + "      \"datasets\"\n"
            + "    ],\n"
            + "    \"draft\": \"n\",\n"
            + "    \"changeDate\": \"2010-02-02T08:00:00Z\",\n"
            + "    \"id\": \"104\",\n"
            + "    \"createDate\": \"2010-02-02T08:00:00Z\",\n"
            + "    \"isPublishedToIntranet\": [\n"
            + "      false\n"
            + "    ],\n"
            + "    \"owner\": \"1\",\n"
            + "    \"logo\": \"/images/logos/7d436f18-8b38-42a4-8df7-1fd0fbaafc8f.png\",\n"
            + "    \"hasxlinks\": \"false\",\n"
            + "    \"featureOfRecord\": \"record\",\n"
            + "    \"isPublishedToGuest\": [\n"
            + "      false\n"
            + "    ],\n"
            + "    \"extra\": \"null\",\n"
            + "    \"documentStandard\": \"iso19139\",\n"
            + "    \"valid\": \"-1\",\n"
            + "    \"isTemplate\": \"n\",\n"
            + "    \"feedbackCount\": \"0\",\n"
            + "    \"rating\": \"0\",\n"
            + "    \"isHarvested\": \"false\",\n"
            + "    \"userSavedCount\": \"0\",\n"
            + "    \"sourceCatalogue\": \"7d436f18-8b38-42a4-8df7-1fd0fbaafc8f\",\n"
            + "    \"op1\": [\n"
            + "      \"2\",\n"
            + "      \"1\"\n"
            + "    ],\n"
            + "    \"op3\": [\n"
            + "      \"2\",\n"
            + "      \"1\"\n"
            + "    ],\n"
            + "    \"op6\": [\n"
            + "      \"0\",\n"
            + "      \"1\",\n"
            + "      \"2\"\n"
            + "    ],\n"
            + "    \"op5\": [\n"
            + "      \"2\",\n"
            + "      \"1\"\n"
            + "    ],\n"
            + "    \"op0\": [\n"
            + "      \"2\",\n"
            + "      \"1\"\n"
            + "    ]\n"
            + "  }\n";

    @Test
    public void test1() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(UNWRAP_SINGLE_VALUE_ARRAYS, true);

        var val = mapper.readValue(json, IndexRecord.class);
        assertEquals("ce6dc729-7ec0-4ba9-baf8-4bc1525120c8", val.getMetadataIdentifier());
        var val2 = mapper.readValue(json2, IndexRecord.class);
        assertEquals("ce6dc729-7ec0-4ba9-baf8-4bc1525120c8", val2.getMetadataIdentifier());
    }
}
