geonetwork:
  schemaplugin:
    schemas:
      - name: "iso19139"
        # Properties that can be used in the batch editing API
        properties :
          - name: "resourceTitleObject"
            xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title"
            value: >
              <gco:CharacterString xmlns:gco="http://www.isotc211.org/2005/gco">{{resourceTitleObject:-}}</gco:CharacterString>

          - name: "resourceIdentifier"
            xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:identifier/gmd:MD_Identifier/gmd:code"
            value: >
              <gco:CharacterString xmlns:gco="http://www.isotc211.org/2005/gco">{{resourceIdentifier.code:-}}</gco:CharacterString>

          - name: "cl_spatialRepresentationType"
            xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialRepresentationType"
            value: >
              <gmd:spatialRepresentationType xmlns:gmd="http://www.isotc211.org/2005/gmd">
                  <gmd:MD_SpatialRepresentationTypeCode
                        codeListValue="{{cl_spatialRepresentationType[0].key:-vector}}" />
                </gmd:spatialRepresentationType>

          - name: "geom"
            xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent"
            value: >
                <gmd:extent xmlns:gco="http://www.isotc211.org/2005/gco"
                                     xmlns:gmd="http://www.isotc211.org/2005/gmd"
                                     gco:nilReason="computedFromDatasource">
                  <gmd:EX_Extent>
                    <gmd:geographicElement>
                      <gmd:EX_GeographicBoundingBox>
                        <gmd:westBoundLongitude>
                         <gco:Decimal>{{geom[0].coordinates[0][0][0]:--180}}</gco:Decimal>
                        </gmd:westBoundLongitude>
                        <gmd:eastBoundLongitude>
                         <gco:Decimal>{{geom[0].coordinates[0][2][0]:-180}}</gco:Decimal>
                        </gmd:eastBoundLongitude>
                        <gmd:southBoundLatitude>
                         <gco:Decimal>{{geom[0].coordinates[0][0][1]:--90}}</gco:Decimal>
                        </gmd:southBoundLatitude>
                        <gmd:northBoundLatitude>
                         <gco:Decimal>{{geom[0].coordinates[0][2][1]:-90}}</gco:Decimal>
                        </gmd:northBoundLatitude>
                      </gmd:EX_GeographicBoundingBox>
                    </gmd:geographicElement>
                  </gmd:EX_Extent>
                </gmd:extent>

          - name: "format"
            xpath: "gmd:distributionInfo/gmd:MD_Distribution/gmd:distributionFormat"
      #          condition: "count(./gmd:distributionInfo/*/gmd:distributionFormat[*/gmd:name/*/text() ='{{formatDescription}}']) = 0"
            value:  >
                  <gmd:distributionFormat
                      xmlns:gco="http://www.isotc211.org/2005/gco"
                      xmlns:gmd="http://www.isotc211.org/2005/gmd"
                      gco:nilReason="computedFromDatasource">
                      <gmd:MD_Format>
                        <gmd:name>
                          <gco:CharacterString>{{format[0]:-}}</gco:CharacterString>
                        </gmd:name>
                        <gmd:version gco:nilReason="unknown">
                          <gco:CharacterString/>
                        </gmd:version>
                      </gmd:MD_Format>
                    </gmd:distributionFormat>

          - name: "link"
            xpath: "gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine"
  #          condition: "count(./gmd:distributionInfo//gmd:onLine[*/gmd:linkage/gmd:URL = '{{datasetUrl}}']) = 0"
            value:  >
              <gmd:onLine xmlns:gco="http://www.isotc211.org/2005/gco"
                                   xmlns:gmd="http://www.isotc211.org/2005/gmd">
                <gmd:CI_OnlineResource>
                  <gmd:linkage>
                    <gmd:URL>{{link[0].url.default}}</gmd:URL>
                  </gmd:linkage>
                  <gmd:protocol>
                    <gco:CharacterString>{{link[0].protocol}}</gco:CharacterString>
                  </gmd:protocol>
                </gmd:CI_OnlineResource>
              </gmd:onLine>



      - name: "iso19115-3.2018"
        properties :
          - name: "resourceTitleObject"
            xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:title"
            value: >
              <gco:CharacterString xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">{{resourceTitleObject:-}}</gco:CharacterString>

          - name: "resourceIdentifier"
            xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:identifier/mcc:MD_Identifier/mcc:code"
            value: >
              <gco:CharacterString xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">{{resourceIdentifier:-}}</gco:CharacterString>

          - name: "cl_spatialRepresentationType"
            xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialRepresentationType"
            value: >
                <mri:spatialRepresentationType xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
                                                                   xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0">
                  <mcc:MD_SpatialRepresentationTypeCode codeListValue="{{cl_spatialRepresentationType:-vector}}"/>
                </mri:spatialRepresentationType>

          - name: "geom"
            xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:extent "
            value: >
                    <mri:extent xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
                                         xmlns:gex="http://standards.iso.org/iso/19115/-3/gex/1.0"
                                         xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                         gco:nilReason="computedFromDatasource">
                       <gex:EX_Extent>
                         <gex:geographicElement>
                           <gex:EX_GeographicBoundingBox>
                             <gex:westBoundLongitude>
                               <gco:Decimal>{{geom[0].coordinates[0][0][0]:--180}}</gco:Decimal>
                             </gex:westBoundLongitude>
                             <gex:eastBoundLongitude>
                               <gco:Decimal>{{geom[0].coordinates[0][2][0]:-180}}</gco:Decimal>
                             </gex:eastBoundLongitude>
                             <gex:southBoundLatitude>
                               <gco:Decimal>{{geom[0].coordinates[0][0][1]:--90}}</gco:Decimal>
                             </gex:southBoundLatitude>
                             <gex:northBoundLatitude>
                               <gco:Decimal>{{geom[0].coordinates[0][2][1]:-90}}</gco:Decimal>
                             </gex:northBoundLatitude>
                           </gex:EX_GeographicBoundingBox>
                         </gex:geographicElement>
                       </gex:EX_Extent>
                    </mri:extent>

          - name: "dateRangeDetails"
            xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:extent/gex:EX_Extent/gex:temporalElement"
            value: >
               <gex:temporalElement xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
                                                                 xmlns:gex="http://standards.iso.org/iso/19115/-3/gex/1.0"
                                                                 xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                                                 xmlns:gml="http://www.opengis.net/gml/3.2"
                                                                 gco:nilReason="computedFromDatasource">
                   <gex:EX_TemporalExtent>
                      <gex:extent>
                         <gml:TimePeriod gml:id="d26013e323a1051934">
                            <gml:beginPosition>{{start.date:-}}</gml:beginPosition>
                            <gml:endPosition>{{end.date:-}}</gml:endPosition>
                         </gml:TimePeriod>
                      </gex:extent>
                   </gex:EX_TemporalExtent>
                  </gex:temporalElement>

          - name: "format"
            xpath: "mdb:distributionInfo/mrd:MD_Distribution/mrd:distributionFormat"
  #            condition: "count(./mdb:distributionInfo/*/mrd:distributionFormat[*/mrd:formatSpecificationCitation/*/cit:title/*/text() ='{{formatDescription}}']) = 0"
            value:  >
              <mrd:distributionFormat xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
                                                xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0"
                                                xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0"
                                                xmlns:mrd="http://standards.iso.org/iso/19115/-3/mrd/1.0"
                                                xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                                gco:nilReason="computedFromDatasource">
                  <mrd:MD_Format>
                    <mrd:formatSpecificationCitation>
                      <cit:CI_Citation>
                        <cit:title>
                          <gco:CharacterString>{{format[0]:-}}</gco:CharacterString>
                        </cit:title>
                      </cit:CI_Citation>
                    </mrd:formatSpecificationCitation>
                  </mrd:MD_Format>
                </mrd:distributionFormat>

          - name: "link"
            xpath: "gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine"
            #          condition: "count(./gmd:distributionInfo//gmd:onLine[*/gmd:linkage/gmd:URL = '{{datasetUrl}}']) = 0"
            value:  >
              <mrd:onLine xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
                                                        xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0"
                                                        xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0"
                                                        xmlns:mrd="http://standards.iso.org/iso/19115/-3/mrd/1.0"
                                                        xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">
                  <cit:CI_OnlineResource>
                    <cit:linkage>
                     <gco:CharacterString>{{link[0].url.default}}</gco:CharacterString>
                    </cit:linkage>
                    <cit:protocol>
                     <gco:CharacterString>{{link[0].protocol}}</gco:CharacterString>
                    </cit:protocol>
                  </cit:CI_OnlineResource>
                </mrd:onLine>
