/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AttributeStatistics
 */
export interface AttributeStatistics {
  /**
   *
   * @type {string}
   * @memberof AttributeStatistics
   */
  name?: string;
  /**
   *
   * @type {{ [key: string]: object; }}
   * @memberof AttributeStatistics
   */
  statistics?: { [key: string]: object };
}

/**
 * Check if a given object implements the AttributeStatistics interface.
 */
export function instanceOfAttributeStatistics(
  value: object
): value is AttributeStatistics {
  return true;
}

export function AttributeStatisticsFromJSON(json: any): AttributeStatistics {
  return AttributeStatisticsFromJSONTyped(json, false);
}

export function AttributeStatisticsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AttributeStatistics {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    statistics: json['statistics'] == null ? undefined : json['statistics'],
  };
}

export function AttributeStatisticsToJSON(
  value?: AttributeStatistics | null
): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    statistics: value['statistics'],
  };
}
