/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GnExtentSpatial } from './GnGnExtentSpatial';
import {
  GnExtentSpatialFromJSON,
  GnExtentSpatialFromJSONTyped,
  GnExtentSpatialToJSON,
} from './GnGnExtentSpatial';
import type { GnExtentTemporal } from './GnGnExtentTemporal';
import {
  GnExtentTemporalFromJSON,
  GnExtentTemporalFromJSONTyped,
  GnExtentTemporalToJSON,
} from './GnGnExtentTemporal';

/**
 * The extent of the features in the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other extents, for example, thermal or pressure ranges.  An array of extents is provided for each extent type (spatial, temporal). The first item in the array describes the overall extent of the data. All subsequent items describe more precise extents, e.g., to identify clusters of data. Clients only interested in the overall extent will only need to access the first extent in the array.
 * @export
 * @interface GnExtent
 */
export interface GnExtent {
  /**
   *
   * @type {GnExtentSpatial}
   * @memberof GnExtent
   */
  spatial?: GnExtentSpatial;
  /**
   *
   * @type {GnExtentTemporal}
   * @memberof GnExtent
   */
  temporal?: GnExtentTemporal;
}

/**
 * Check if a given object implements the GnExtent interface.
 */
export function instanceOfGnExtent(value: object): value is GnExtent {
  return true;
}

export function GnExtentFromJSON(json: any): GnExtent {
  return GnExtentFromJSONTyped(json, false);
}

export function GnExtentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GnExtent {
  if (json == null) {
    return json;
  }
  return {
    spatial:
      json['spatial'] == null
        ? undefined
        : GnExtentSpatialFromJSON(json['spatial']),
    temporal:
      json['temporal'] == null
        ? undefined
        : GnExtentTemporalFromJSON(json['temporal']),
  };
}

export function GnExtentToJSON(value?: GnExtent | null): any {
  if (value == null) {
    return value;
  }
  return {
    spatial: GnExtentSpatialToJSON(value['spatial']),
    temporal: GnExtentTemporalToJSON(value['temporal']),
  };
}
