/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GnOgcApiRecordsExceptionDto
 */
export interface GnOgcApiRecordsExceptionDto {
    /**
     * 
     * @type {string}
     * @memberof GnOgcApiRecordsExceptionDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof GnOgcApiRecordsExceptionDto
     */
    description?: string;
}

/**
 * Check if a given object implements the GnOgcApiRecordsExceptionDto interface.
 */
export function instanceOfGnOgcApiRecordsExceptionDto(value: object): value is GnOgcApiRecordsExceptionDto {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function GnOgcApiRecordsExceptionDtoFromJSON(json: any): GnOgcApiRecordsExceptionDto {
    return GnOgcApiRecordsExceptionDtoFromJSONTyped(json, false);
}

export function GnOgcApiRecordsExceptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GnOgcApiRecordsExceptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function GnOgcApiRecordsExceptionDtoToJSON(value?: GnOgcApiRecordsExceptionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

