/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A list of available distributions of the resource.
 * @export
 * @interface GnOgcApiRecordsFormatDto
 */
export interface GnOgcApiRecordsFormatDto {
    /**
     * 
     * @type {string}
     * @memberof GnOgcApiRecordsFormatDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GnOgcApiRecordsFormatDto
     */
    mediaType?: string;
}

/**
 * Check if a given object implements the GnOgcApiRecordsFormatDto interface.
 */
export function instanceOfGnOgcApiRecordsFormatDto(value: object): value is GnOgcApiRecordsFormatDto {
    return true;
}

export function GnOgcApiRecordsFormatDtoFromJSON(json: any): GnOgcApiRecordsFormatDto {
    return GnOgcApiRecordsFormatDtoFromJSONTyped(json, false);
}

export function GnOgcApiRecordsFormatDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GnOgcApiRecordsFormatDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'mediaType': json['mediaType'] == null ? undefined : json['mediaType'],
    };
}

export function GnOgcApiRecordsFormatDtoToJSON(value?: GnOgcApiRecordsFormatDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'mediaType': value['mediaType'],
    };
}

