/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GnProcessReport
 */
export interface GnProcessReport {
  /**
   *
   * @type {string}
   * @memberof GnProcessReport
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof GnProcessReport
   */
  errorMessage?: string;
}

/**
 * Check if a given object implements the GnProcessReport interface.
 */
export function instanceOfGnProcessReport(
  value: object
): value is GnProcessReport {
  return true;
}

export function GnProcessReportFromJSON(json: any): GnProcessReport {
  return GnProcessReportFromJSONTyped(json, false);
}

export function GnProcessReportFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GnProcessReport {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'] == null ? undefined : json['status'],
    errorMessage:
      json['errorMessage'] == null ? undefined : json['errorMessage'],
  };
}

export function GnProcessReportToJSON(value?: GnProcessReport | null): any {
  if (value == null) {
    return value;
  }
  return {
    status: value['status'],
    errorMessage: value['errorMessage'],
  };
}
