/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An identifier for the resource assigned by an external (to the catalog) entity.
 * @export
 * @interface OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto
 */
export interface OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto {
    /**
     * A reference to an authority or identifier for a knowledge organization system from which the external identifier was obtained. It is recommended that the identifier be a resolvable URI.
     * @type {string}
     * @memberof OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto
     */
    scheme?: string;
    /**
     * The value of the identifier.
     * @type {string}
     * @memberof OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto
     */
    value: string;
}

/**
 * Check if a given object implements the OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto interface.
 */
export function instanceOfOgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto(value: object): value is OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDtoFromJSON(json: any): OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto {
    return OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDtoFromJSONTyped(json, false);
}

export function OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'value': json['value'],
    };
}

export function OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDtoToJSON(value?: OgcApiRecordsRecordCommonPropertiesExternalIdsInnerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scheme': value['scheme'],
        'value': value['value'],
    };
}

