/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OgcApiRecordsLinkBaseDto
 */
export interface OgcApiRecordsLinkBaseDto {
  /**
   * The type or semantics of the relation.
   * @type {string}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  rel?: string;
  /**
   * A hint indicating what the media type of the result of dereferencing the link should be.
   * @type {string}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  type?: string;
  /**
   * A hint indicating what the language of the result of dereferencing the link should be.
   * @type {string}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  hreflang?: string;
  /**
   * Used to label the destination of a link such that it can be used as a human-readable identifier.
   * @type {string}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  length?: number;
  /**
   * Date of creation of the resource pointed to by the link.
   * @type {Date}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  created?: Date;
  /**
   * Most recent date on which the resource pointed to by the link was changed.
   * @type {Date}
   * @memberof OgcApiRecordsLinkBaseDto
   */
  updated?: Date;
}

/**
 * Check if a given object implements the OgcApiRecordsLinkBaseDto interface.
 */
export function instanceOfOgcApiRecordsLinkBaseDto(
  value: object
): value is OgcApiRecordsLinkBaseDto {
  return true;
}

export function OgcApiRecordsLinkBaseDtoFromJSON(
  json: any
): OgcApiRecordsLinkBaseDto {
  return OgcApiRecordsLinkBaseDtoFromJSONTyped(json, false);
}

export function OgcApiRecordsLinkBaseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OgcApiRecordsLinkBaseDto {
  if (json == null) {
    return json;
  }
  return {
    rel: json['rel'] == null ? undefined : json['rel'],
    type: json['type'] == null ? undefined : json['type'],
    hreflang: json['hreflang'] == null ? undefined : json['hreflang'],
    title: json['title'] == null ? undefined : json['title'],
    length: json['length'] == null ? undefined : json['length'],
    created: json['created'] == null ? undefined : new Date(json['created']),
    updated: json['updated'] == null ? undefined : new Date(json['updated']),
  };
}

export function OgcApiRecordsLinkBaseDtoToJSON(
  value?: OgcApiRecordsLinkBaseDto | null
): any {
  if (value == null) {
    return value;
  }
  return {
    rel: value['rel'],
    type: value['type'],
    hreflang: value['hreflang'],
    title: value['title'],
    length: value['length'],
    created:
      value['created'] == null ? undefined : value['created'].toISOString(),
    updated:
      value['updated'] == null ? undefined : value['updated'].toISOString(),
  };
}
