/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork API
 * This API exposes endpoints to GeoNetwork API.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RasterBand
 */
export interface RasterBand {
  /**
   *
   * @type {number}
   * @memberof RasterBand
   */
  band?: number;
}

/**
 * Check if a given object implements the RasterBand interface.
 */
export function instanceOfRasterBand(value: object): value is RasterBand {
  return true;
}

export function RasterBandFromJSON(json: any): RasterBand {
  return RasterBandFromJSONTyped(json, false);
}

export function RasterBandFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RasterBand {
  if (json == null) {
    return json;
  }
  return {
    band: json['band'] == null ? undefined : json['band'],
  };
}

export function RasterBandToJSON(value?: RasterBand | null): any {
  if (value == null) {
    return value;
  }
  return {
    band: value['band'],
  };
}
