--
-- SPDX-FileCopyrightText: 2001 FAO-UN and others <geonetwork@osgeo.org>
--
-- SPDX-License-Identifier: GPL-2.0-or-later
--
CREATE TABLE IF NOT EXISTS APP_CONFIGS (
  APP VARCHAR(255) NOT NULL,
  PROFILE VARCHAR(255) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  CONFIG_PARAM VARCHAR(255) NOT NULL,
  CONFIG_VALUE TEXT NOT NULL,
  INTERNAL BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY (APP, PROFILE, LABEL, CONFIG_PARAM)
);

CREATE INDEX IF NOT EXISTS IDX_APP_CONFIGS_LOWER_APP ON APP_CONFIGS (LOWER(APP), PROFILE, LABEL);
CREATE INDEX IF NOT EXISTS IDX_APP_CONFIGS_PARAM ON APP_CONFIGS (CONFIG_PARAM);
