/* tslint:disable */
/* eslint-disable */
/**
 * GeoNetwork 4.4.5 OpenAPI Documentation
 * This is the description of the GeoNetwork OpenAPI. Use this API to manage your catalog.
 *
 * The version of the OpenAPI document: 4.4.5
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { MapService } from '../models/index';
import { MapServiceFromJSON, MapServiceToJSON } from '../models/index';

/**
 *
 */
export class MapservicesApi extends runtime.BaseAPI {
  /**
   * Return the list of mapservices. mapservices are used to identify secured map services.
   * Get mapservices
   */
  async getMapservicesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<MapService>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/mapservices`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue =>
      jsonValue.map(MapServiceFromJSON)
    );
  }

  /**
   * Return the list of mapservices. mapservices are used to identify secured map services.
   * Get mapservices
   */
  async getMapservices(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<MapService>> {
    const response = await this.getMapservicesRaw(initOverrides);
    return await response.value();
  }
}
