/*
 * (c) 2003 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license,
 * available at the root application directory.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.06.04 at 11:39:43 AM CEST
//

package org.geonetwork.schemas.model.schemaident;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Define the information used to determine whether a metadata record is defined using this schema.
 *
 * <p>Java class for autodetectType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="autodetectType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="elements" type="{http://geonetwork-opensource.org/schemas/schema-ident}elementsType"/&gt;
 *         &lt;element name="attributes" type="{http://geonetwork-opensource.org/schemas/schema-ident}attributesType"/&gt;
 *         &lt;element name="namespaces" type="{http://geonetwork-opensource.org/schemas/schema-ident}namespacesType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "autodetectType",
        propOrder = {"namespaces", "attributes", "elements"})
public class AutodetectType {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String namespaces;

    protected AttributesType attributes;
    protected ElementsType elements;

    /**
     * Gets the value of the namespaces property.
     *
     * @return possible object is {@link String }
     */
    public String getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     *
     * @param value allowed object is {@link String }
     */
    public void setNamespaces(String value) {
        this.namespaces = value;
    }

    /**
     * Gets the value of the attributes property.
     *
     * @return possible object is {@link AttributesType }
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     *
     * @param value allowed object is {@link AttributesType }
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the elements property.
     *
     * @return possible object is {@link ElementsType }
     */
    public ElementsType getElements() {
        return elements;
    }

    /**
     * Sets the value of the elements property.
     *
     * @param value allowed object is {@link ElementsType }
     */
    public void setElements(ElementsType value) {
        this.elements = value;
    }
}
