/*
 * (c) 2003 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license,
 * available at the root application directory.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.06.04 at 11:39:43 AM CEST
//

package org.geonetwork.schemas.model.schemaident;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Define the formatters for the metadata records using this schema.
 *
 * <p>Java class for formatters complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="formatters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formatter" type="{http://geonetwork-opensource.org/schemas/schema-ident}formatter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "formatters",
        propOrder = {"formatters"})
public class Formatters {

    @XmlElement(name = "formatter")
    protected List<Formatter> formatters;

    /**
     * Gets the value of the formatters property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
     * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the formatters property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getFormatters().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link Formatter }
     */
    public List<Formatter> getFormatters() {
        if (formatters == null) {
            formatters = new ArrayList<Formatter>();
        }
        return this.formatters;
    }
}
