name: Build GeoNetwork 5 docker image and push to ghcr.io

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/gn5-main:latest"
          
          # First build the project
          mvn clean install -DskipTests
          
          # Then build the Docker image for the main app only
          if [[ "${{ github.event_name }}" == "push" ]]; then
            mvn spring-boot:build-image \
              -pl src/apps/geonetwork \
              -Dspring-boot.build-image.imageName=${IMAGE_NAME} \
              -Dspring-boot.build-image.publish=true
          else
            mvn spring-boot:build-image \
              -pl src/apps/geonetwork \
              -Dspring-boot.build-image.imageName=${IMAGE_NAME}
          fi

