geonetwork:
  schemas:
    iso19115-3:
      name: iso19115-3
      id: 93f66207-621a-4610-813f-38494a51d121
      version: 1.0
      standardTitle:
        eng: Geographic information - Metadata
        fre: Information géographique - Métadonnées
      standardDescription:
        eng: |
          The objective of ISO 19115 is to provide a model for describing information or resources
          that can have geographic extents. This part of ISO 19115 is intended to be used by information system
          analysts, program planners, and developers of information systems, as well as others in order to define
          basic principles and requirements for standardized description of information resources. This part of
          ISO  19115 defines metadata elements, their properties, and the relationships between elements, and
          establishes a common set of metadata terminology, definitions, and extension procedures.

          Although the primary purpose of this part of ISO  19115 is to describe digital information that has a
          geographic extent, it can be used to describe all types of resources including textual documents,
          initiatives, software, sensors, non-geographic information, product specifications and repositories, i.e. it can be
          used to describe information resources that do not have geographic extent. Some domains have their
          own metadata standards, such as the Dublin Core for libraries. If necessary such standards and this part
          of ISO 19115 could be profiled to create a Community Schema.

          This schema also includes:

          - Describe imagery data (covered by ISO19115-2)

          - Embed data model (feature catalogue) in the dataset record (covered by ISO19110)

          - Data quality described using ISO19157

      standardUrl:
        eng: http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=32579
      schemaLocation: http://standards.iso.org/iso/19115/-3/mdb/2.0 https://schemas.isotc211.org/19115/-3/mdb/2.0/mdb.xsd
      primeNamespace: http://standards.iso.org/iso/19115/-3/mdb/2.0
      autodetect: count(mdb:MD_Metadata|cit:CI_Responsibility|cit:CI_Organisation|mcc:MD_BrowseGraphic|mrs:MD_ReferenceSystem|mrd:MD_Format|mdq:DQ_DomainConsistency|mdq:DQ_CompletenessCommission|mdq:DQ_CompletenessOmission|mdq:DQ_ConceptualConsistency|mdq:DQ_FormatConsistency|mdq:DQ_AbsoluteExternalPositionalAccuracy|mdq:DQ_AccuracyOfATimeMeasurement|mdq:DQ_Confidence|mdq:DQ_GriddedDataPositionalAccuracy|mdq:DQ_Homogeneity|mdq:DQ_NonQuantitativeAttributeCorrectness|mdq:DQ_QuantitativeAttributeAccuracy|mdq:DQ_RelativeInternalPositionalAccuracy|mdq:DQ_Representativity|mdq:DQ_TemporalConsistency|mdq:DQ_TemporalValidity|mdq:DQ_ThematicClassificationCorrectness|mdq:DQ_TopologicalConsistency|mdq:DQ_UsabilityElement|mco:MD_Constraints|mco:MD_LegalConstraints|mco:MD_SecurityConstraints) > 0

      formatters:
        - name: xml
          title:
          officialProfileName: http://geonetwork.net/def/profile/raw-xml
          contentType: application/xml
        - name: datacite
          title:
          officialProfileName: http://geonetwork.net/def/profile/datacite
          contentType: application/xml
        - name: dcat
          title:
          officialProfileName: http://geonetwork.net/def/profile/dcat
          contentType: application/rdf+xml
        - name: eu-dcat-ap
          title:
          officialProfileName: http://geonetwork.net/def/profile/eu-dcat-ap
          contentType: application/rdf+xml
        - name: eu-dcat-ap-hvd
          title:
          officialProfileName: http://geonetwork.net/def/profile/eu-dcat-ap-hvd
          contentType: application/rdf+xml
        - name: eu-geodcat-ap
          title:
          officialProfileName: http://geonetwork.net/def/profile/eu-geodcat-ap
          contentType: application/rdf+xml

      #      Filters defined which elements should be removed
      #      depending on user privileges.
      filters:
        #          All elements having a nilReason attribute
        #            set to withheld, then users needs to have
        #            the edit privilege in order to be able to see
        #            the information. When filtered the element is
        #            preserved but with no content in.
        - xpath: .//*[@gco:nilReason = 'withheld']
          jsonpath: $.*[?(@.nilReason == 'withheld')]
          ifNotOperation: editing
          keepMarkedElement: true
        #          All online source having WMS protocol are filtered
        #          to user not having dynamic privilege.
        - xpath: .//mrd:onLine[starts-with(*/cit:protocol/gco:CharacterString, 'OGC:WMS')]
          jsonpath: $['link'][?(@.protocol =~ /OGC:WMS.*?/i)]
          ifNotOperation: dynamic
        #          All online source having the following protocols
        #          are filtered when user does not have download
        #          privilege.
        - xpath: >
             .//mrd:onLine[contains(*/cit:protocol/gco:CharacterString, 'DOWNLOAD') or
             */cit:protocol/gco:CharacterString = 'FILE' or
             */cit:protocol/gco:CharacterString = 'DB' or
             */cit:protocol/gco:CharacterString = 'COPYFILE']
          jsonpath: $['link'][?(@.protocol =~ /(DOWNLOAD|FILE|DB|COPYFILE).*?/i)]
          ifNotOperation: download

      substitutes:
        - field: mri:AbstractMD_Identification
          substitutes:
            - srv:SV_ServiceIdentification
            - mri:MD_DataIdentification
        - field: gml:VerticalCS
        - field: gml:VerticalDatum
        - field: gml:CoordinateSystemAxis

      suggestions:
        - field: gcx:Anchor
          suggestions:
            - xlink:href
        - field: cit:CI_Date
          suggestions:
            - cit:date
        - field: cit:date
          suggestions:
            - gco:Date
        - field: mcc:code
          suggestions:
            - gco:CharacterString
            - gcx:FileName
            - gcx:Anchor
        - field: mri:language
          suggestions:
            - gco:CharacterString
            - mri:LanguageCode
        - field: srv:coupledResource
          suggestions:
            - srv:SV_CoupledResource
        - field: srv:parameters
          suggestions:
            - srv:SV_Parameter
        - field: srv:direction
          suggestions:
            - srv:SV_ParameterDirection
        - field: cit:CI_OnlineResource
          suggestions:
            - cit:protocol
            - cit:name
            - cit:description
            - cit:function
        - field: mrd:transferOptions
          suggestions:
            - mrd:MD_DigitalTransferOptions
        - field: mrd:MD_DigitalTransferOptions
          suggestions:
            - mrd:onLine
        - field: cit:CI_Individual
          suggestions:
            - cit:name
            - cit:address
        - field: cit:CI_Organisation
          suggestions:
            - cit:name
            - cit:contactInfo
        - field: cit:CI_Contact
          suggestions:
            - cit:address
        - field: cit:CI_Telephone
          suggestions:
            - cit:number
            - cit:numberType
        - field: cit:CI_Address
          suggestions:
            - cit:electronicMailAddress
        - field: mri:MD_Keywords
          suggestions:
            - mri:type
        - field: gex:EX_Extent
          suggestions:
            - gex:geographicElement
        - field: gex:EX_TemporalExtent
          suggestions:
            - gex:extent
        - field: gex:polygon
          suggestions:
            - gml:Polygon
        - field: gex:extent
          suggestions:
            - gex:EX_Extent
        - field: gml:TimePeriod
          suggestions:
            - gml:beginPosition
            - gml:endPosition
        - field: gex:EX_GeographicBoundingBox
          suggestions:
            - gex:westBoundLongitude
            - gex:eastBoundLongitude
            - gex:southBoundLatitude
            - gex:northBoundLatitude
        - field: mcc:attributes
          suggestions:
            - uuidref
        - field: mcc:features
          suggestions:
            - uuidref
        - field: mcc:featureInstances
          suggestions:
            - uuidref
        - field: mcc:attributeInstances
          suggestions:
            - uuidref
        - field: mrc:featureTypes
          suggestions:
            - uuidref
        - field: srv:operatesOn
          suggestions:
            - uuidref
        - field: gml:Polygon
          suggestions:
            - srsName
        - field: gml:descriptionReference
          suggestions:
            - xlink:href
        - field: mco:MD_Constraints
          suggestions:
            - mco:useLimitation
        - field: mco:MD_LegalConstraints
          suggestions:
            - mco:useLimitation
            - mco:accessConstraints
            - mco:useConstraints
            - mco:otherContraints
        - field: mco:MD_SecurityContraints
          suggestions:
            - mco:classification
            - mco:useLimitation
        - field: gfc:FC_FeatureType
          suggestions:
            - gfc:typeName
        - field: gfc:listedValue
          suggestions:
            - gfc:FC_ListedValue
        - field: gfc:FC_ListedValue
          suggestions:
            - gfc:code
        - field: gfc:FC_AssociationRole
          suggestions:
            - gfc:definition
        - field: gfc:constrainedBy
          suggestions:
            - gfc:FC_Constraint
        - field: gfc:FC_FeatureAttribute
          suggestions:
            - gfc:memberName
            - gfc:definition
            - gfc:valueType
            - gfc:featureType
        - field: gfc:inheritsTo
          suggestions:
            - gfc:FC_InheritanceRelation
        - field: gfc:inheritsFrom
          suggestions:
            - gfc:FC_InheritanceRelation
