geonetwork:
  schemas:
    iso19139:
      name: iso19139
      id: 3f95190a-dde4-11df-8626-001c2346de4c</id>
      version: 1.0
      standardTitle:
        eng: Geographic information - Metadata (iso19139:2007)
        fre: Information géographique - Métadonnées (iso19139:2007)
      standardDescription:
        eng: |
          ISO 19115 defines the schema required for describing geographic information and services by
          means of metadata. It provides information about the identification, the extent, the quality,
          the spatial and temporal aspects, the content, the spatial reference, the portrayal,
          distribution, and other properties of digital geographic data and services.

          ISO 19115 is applicable to:

            - the cataloguing of all types of resources, clearinghouse activities, and the full description of datasets and services;

            - geographic services, geographic datasets, dataset series, and individual geographic features and feature properties.

          ISO 19115 defines:

            - mandatory and conditional metadata sections, metadata entities, and metadata elements;

            - the minimum set of metadata required to serve most metadata applications (data discovery,
              determining data fitness for use, data access, data transfer, and use of digital data and
              services);

            - optional metadata elements to allow for a more extensive standard description of resources, if
              required;

            - a method for extending metadata to fit specialized needs.

            Though ISO 19115 is applicable to digital data and services, its principles can be extended to
            many other types of resources such as maps, charts, and textual documents as well as
            non-geographic data. Certain conditional metadata elements might not apply to these other forms
            of data.
      standardUrl:
        eng: https://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=53798
      schemaLocation: http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd
      primeNamespace: http://www.isotc211.org/2005/gmd
      autodetect: count(gmd:MD_Metadata|gmd:CI_ResponsibleParty|gmd:DQ_DomainConsistency|gmd:MD_Format|gmd:EX_Extent) > 0

      formatters:
        - name: xml
          title:
          officialProfileName: http://geonetwork.net/def/profile/raw-xml
          contentType: application/xml
        - name: datacite
          title:
          officialProfileName: http://geonetwork.net/def/profile/datacite
          contentType: application/xml
        - name: dcat
          title:
          officialProfileName: http://geonetwork.net/def/profile/dcat
          contentType: application/rdf+xml
        - name: eu-dcat-ap
          title:
          officialProfileName: http://geonetwork.net/def/profile/eu-dcat-ap
          contentType: application/rdf+xml
        - name: eu-dcat-ap-hvd
          title:
          officialProfileName: http://geonetwork.net/def/profile/eu-dcat-ap-hvd
          contentType: application/rdf+xml
        - name: eu-geodcat-ap
          title:
          officialProfileName: http://geonetwork.net/def/profile/eu-geodcat-ap
          contentType: application/rdf+xml

      #      Filters defined which elements should be removed
      #      depending on user privileges.
      filters:
        #          All elements having a nilReason attribute
        #            set to withheld, then users needs to have
        #            the edit privilege in order to be able to see
        #            the information. When filtered the element is
        #            preserved but with no content in.
        - xpath: .//*[@gco:nilReason = 'withheld']
          jsonpath: $.*[?(@.nilReason == 'withheld')]
          ifNotOperation: editing
          keepMarkedElement: true
        #          All online source having WMS protocol are filtered
        #          to user not having dynamic privilege.
        - xpath: .//mrd:onLine[starts-with(*/cit:protocol/gco:CharacterString, 'OGC:WMS')]
          jsonpath: $['link'][?(@.protocol =~ /OGC:WMS.*?/i)]
          ifNotOperation: dynamic
        #          All online source having the following protocols
        #          are filtered when user does not have download
        #          privilege.
        - xpath: >
             .//mrd:onLine[contains(*/cit:protocol/gco:CharacterString, 'DOWNLOAD') or
             */cit:protocol/gco:CharacterString = 'FILE' or
             */cit:protocol/gco:CharacterString = 'DB' or
             */cit:protocol/gco:CharacterString = 'COPYFILE']
          jsonpath: $['link'][?(@.protocol =~ /(DOWNLOAD|FILE|DB|COPYFILE).*?/i)]
          ifNotOperation: download

      substitutes:
        - field: gmd:AbstractMD_Identification
          substitutes:
            - srv:SV_ServiceIdentification
            - gmd:MD_DataIdentification
        - field: gml:VerticalCS
        - field: gml:VerticalDatum
        - field: gml:CoordinateSystemAxis

      suggestions:
        - field: gmd:contactInstructions
          suggestions:
            - gco:CharacterString
            - gmx:FileName
        - field: gmd:otherCitationDetails
          suggestions:
            - gco:CharacterString
            - gmx:FileName
            - gmx:Anchor
        - field: gmd:hierarchyLevel
          suggestions:
            - gmd:MD_ScopeCode
        - field: gmx:Anchor
          suggestions:
            - xlink:href
        - field: gmd:code
          suggestions:
            - gco:CharacterString
            - gmx:FileName
            - gmx:Anchor
        - field: gmd:language
          suggestions:
            - gco:CharacterString
            - gmd:LanguageCode
        - field: gmx:FileName
          suggestions:
            - src
        - field: srv:coupledResource
          suggestions:
            - srv:SV_CoupledResource
        - field: srv:parameters
          suggestions:
            - srv:SV_Parameter
        - field: srv:direction
          suggestions:
            - srv:SV_ParameterDirection
        - field: gmd:CI_OnlineResource
          suggestions:
            - gmd:protocol
            - gmd:name
            - gmd:description
        - field: gmd:transferOptions
          suggestions:
            - gmd:MD_DigitalTransferOptions
        - field: gmd:MD_DigitalTransferOptions
          suggestions:
            - gmd:onLine
        - field: gmd:CI_ResponsibleParty
          suggestions:
            - gmd:organisationName
            - gmd:individualName
            - gmd:contactInfo
        - field: gmd:CI_Contact
          suggestions:
            - gmd:address
        - field: gmd:CI_Address
          suggestions:
            - gmd:electronicMailAddress
        - field: gmd:MD_Keywords
          suggestions:
            - gmd:type
        - field: gmd:date
          suggestions:
            - gco:Date
        - field: gmd:EX_Extent
          suggestions:
            - gmd:temporalElement
            - gmd:geographicElement
            - gmd:verticalElement
        - field: gmd:EX_TemporalExtent
          suggestions:
            - gmd:extent
        - field: gmd:polygon
          suggestions:
            - gml:Polygon
        - field: gmd:extent
          suggestions:
            - gmd:EX_Extent
        - field: gml:TimePeriod
          suggestions:
            - gml:beginPosition
            - gml:endPosition
        - field: gmd:EX_GeographicBoundingBox
          suggestions:
            - gmd:westBoundLongitude
            - gmd:eastBoundLongitude
            - gmd:southBoundLatitude
            - gmd:northBoundLatitude
        - field: gmd:attributes
          suggestions:
            - uuidref
        - field: gmd:features
          suggestions:
            - uuidref
        - field: gmd:featureInstances
          suggestions:
            - uuidref
        - field: gmd:attributeInstances
          suggestions:
            - uuidref
        - field: gmd:propertyType
          suggestions:
            - uuidref
        - field: gmd:featureType
          suggestions:
            - uuidref
        - field: gmd:featureAttribute
          suggestions:
            - uuidref
        - field: srv:operatesOn
          suggestions:
            - uuidref
        - field: gmd:source
          suggestions:
            - uuidref
        - field: gml:Polygon
          suggestions:
            - srsName
        - field: gml:descriptionReference
          suggestions:
            - xlink:href
        - field: gmd:MD_Constraints
          suggestions:
            - gmd:useLimitation
        - field: gmd:MD_LegalConstraints
          suggestions:
            - gmd:useLimitation
            - gmd:accessConstraints
            - gmd:useConstraints
            - gmd:otherContraints
        - field: gmd:MD_SecurityContraints
          suggestions:
            - gmd:classification
            - gmd:useLimitation
